
export class MaintenanceError {
    public static maintenance  ={
    "resolve" : "Resolved",
    "forward" : "Forward",
    "reverse" : "Reverse",
    "stop" : "Stop",
    "tare" : "Tare",
    "calibrate": "Calibrate",
    "open":"Open",
    "close" : "Close",  
    "plastic" : "Plastic",
    "glass" : "Glass",
    "FC_RIGHT_DOCK_ROTATION" : "Right Conveyor Rotation Error",
    "FC_LEFT_DOCK_ROTATION" : "Left Conveyor Rotation Error",
    "LOADCELL_ERROR" : "Loadcell Error",
    "PLASTIC_MOTOR_JAM" : "Plastic Shredder Jam",
    "PLASTIC_MOTOR_ROTATION" : "Plastic Shredder Power Transmission Error",
    "ALUMINIUM_MOTOR_JAM" : "Aluminium Shredder Jam",
    "ALUMINIUM_MOTOR_ROTATION" : "Aluminium Shredder Power Transmission Error",
    "GLASS_MOTOR_JAM" : "Glass Shredder Jam",
    "GLASS_MOTOR_ROTATION" : "Glass Shredder Power Transmission Error",
    "FRONT_TOP_DOOR_OPEN" : "Front Top Door Open",
    "FRONT_BOTTOM_DOOR_OPEN" : "Front Bottom Door Open",
    "LEFT_DOOR_OPEN" : "Left Door Open",
    "RIGHT_DOOR_OPEN" : "Right Door Open",
    "BACK_DOOR_OPEN" : "Back Door Open",
    "EMG_STATUS" : "Emergency On",
    "BIN_FULL_COUNT" : "Storage Bin Full",
    "REMOVE_BOTTLE" : "Please remove container from the Conveyor and try inserting again.",
    "DOOR_ERROR" : "Sorter Door Error",
    "PLASTIC_SORTER" : "Plastic Sorter Flap Error",
    "GLASS_SORTER" : "Glass Sorter Flap Error",
    "SHREDDER_CLEAN_CYCLE" : "Machine is under cleaning process. Please wait for the green light to insert containers.",
    "PLASTIC_BIN_FULL_COUNT" : "Plastic Storage Bin Full",
    "GLASS_BIN_FULL_COUNT" : "Glass Storage Bin Full",
    "ALUMINIUMN_BIN_FULL_COUNT" : "Metal Cans Storage Bin Full",
    "PRINTER_ROLE_STATUS":"Print paper has finished please contact store manager to refill"   
}
}